const initialState = {
  isLogined: false,
  loginPending: false,
  loginError: null,
  addPatientPending: false,
  addPatientError: null,
  deletePatientPending: false,
  deletePatientError: null,
  getPatientsListPending: false,
  getPatientsListError: null,
  updatePatientPending: false,
  updatePatientError: null,
  addVisitePending: false,
  addVisiteError: null,
  deleteVisitePending: false,
  deleteVisiteError: null,
  updateVisitePending: false,
  updateVisiteError: null,
  getVisitesListPending: false,
  getVisitesListError: null,
  findVssByOrdIdPending: false,
  findVssByOrdIdError: null,
  getOrdonnancesListPending: false,
  getOrdonnancesListError: null,
  updateOrdonnancePending: false,
  updateOrdonnanceError: null,
  findVsByVsIdPending: false,
  findVsByVsIdError: null,
  findOrdByOrdIdPending: false,
  findOrdByOrdIdError: null,
  findVsDtlByVsIdPending: false,
  findVsDtlByVsIdError: null,
  findPatientDtlByVsIdPending: false,
  findPatientDtlByVsIdError: null,
  updatePeByVsIdAndPidPending: false,
  updatePeByVsIdAndPidError: null,
  addPeByVsIdAndPidPending: false,
  addPeByVsIdAndPidError: null,
  addEmByVsIdPending: false,
  addEmByVsIdError: null,
  updateEmByVsIdPending: false,
  updateEmByVsIdError: null,
};

export default initialState;
