const initialState = {
  isLogined: false,
  loginPending: false,
  loginError: null,
  addPatientPending: false,
  addPatientError: null,
  deletePatientPending: false,
  deletePatientError: null,
  getPatientsListPending: false,
  getPatientsListError: null,
  updatePatientPending: false,
  updatePatientError: null,
  addVisitePending: false,
  addVisiteError: null,
  deleteVisitePending: false,
  deleteVisiteError: null,
  updateVisitePending: false,
  updateVisiteError: null,
  getVisitesListPending: false,
  getVisitesListError: null,
  findVssByOrdIdPending: false,
  findVssByOrdIdError: null,
  getOrdonnancesListPending: false,
  getOrdonnancesListError: null,
  updateOrdonnancePending: false,
  updateOrdonnanceError: null,
  findVsByVsIdPending: false,
  findVsByVsIdError: null,
  findOrdByOrdIdPending: false,
  findOrdByOrdIdError: null,
};

export default initialState;
